site_name: Robase Documentation
site_url: http://info.arvorian.com/Robase-2.0.0/
repo_url: https://github.com/Arvoria/Robase-2.0.0
repo_name: Arvoria/Robase-2.0.0

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css: 
  - stylesheets/extra.css
  - stylesheets/admonitions/stop.css

theme:
  name: material
  custom_dir: overrides
  font:
    text: Encode Sans
    code: Fira Code
  logo: img/ai-logo-flat.svg

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ArvorianDevs_
  social:
    - icon: octicons/logo-github-16
      link: https://github.com/Arvoria

nav: 
  - 'Home': 'index.md'
  - "About":
    - 'Introduction': 'introduction.md'
    - 'Why Robase?': 'introduction/#whats-the-purpose'
    - 'Limitations': 'introduction/#storage-limitations'
  - "Guide": 
    - 'Installing Robase': 'Guide/installation.md'
    - 'Setting up Robase': 'Guide/setup.md'
    - 'Robase Examples': 'Guide/examples.md'
  - "API Reference": 'api.md'
    

