[package]
name = "shanebutt/robase-service"
version = "2.2.0"
license = "MIT"
authors = [ "Shane Butt <shaneslothrsf@gmail.com>" ]
description = "A simple to use promise-driven wrapper for the Firebase RESTful API."

registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]